export const DEMO_USER_ID = 'cmprffoo10000jrm79fshecm0';

export const FALLBACKS = {
  clients: [
    {
      id: 'client-1',
      firstName: 'Ana',
      lastName: 'García',
      email: 'ana@example.com',
      phone: '123456789',
      status: 'RECURRING',
      notes: 'Prefiere tonos nude',
      preferredStylist: 'Maye',
      birthday: '1990-05-15',
      totalVisits: 5,
      lastAppointment: { date: '2024-05-20', startTime: '10:00', status: 'COMPLETED' },
      userId: DEMO_USER_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'client-2',
      firstName: 'Lucía',
      lastName: 'Martínez',
      email: 'lucia@example.com',
      phone: '987654321',
      status: 'NEW',
      notes: 'Alergia a algunos acrílicos',
      preferredStylist: 'Maye',
      birthday: '1995-11-02',
      totalVisits: 0,
      lastAppointment: null,
      userId: DEMO_USER_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  services: [
    {
      id: 'service-1',
      name: 'Manicura Rusa',
      description: 'Limpieza profunda de cutícula y esmaltado semipermanente',
      duration: 90,
      price: 35.0,
      category: 'GENERAL',
      active: true,
      userId: DEMO_USER_ID,
    },
    {
      id: 'service-2',
      name: 'Uñas Acrílicas XL',
      description: 'Extensión con acrílico y diseño avanzado',
      duration: 150,
      price: 60.0,
      category: 'COLORING',
      active: true,
      userId: DEMO_USER_ID,
    },
  ],
  appointments: [
    {
      id: 'app-1',
      date: new Date().toISOString().split('T')[0],
      startTime: '10:00',
      endTime: '11:30',
      status: 'CONFIRMED',
      notes: 'Diseño floral',
      clientId: 'client-1',
      serviceId: 'service-1',
      userId: DEMO_USER_ID,
    },
  ],
  dashboard: {
    stats: {
      totalClients: 14,
      totalAppointments: 20,
      revenue: 1200,
      activeServices: 8,
    },
    pipeline: {
      NEW: 4,
      RECURRING: 7,
      INACTIVE: 3,
    },
    todayAppointments: [
      {
        id: 'app-1',
        client: { firstName: 'Ana', lastName: 'García' },
        service: { name: 'Manicura Rusa' },
        startTime: '10:00',
        status: 'CONFIRMED',
      },
    ],
    recentActivity: [
      { id: 'act-1', type: 'APPOINTMENT_CREATED', message: 'Nueva cita para Ana García', date: new Date().toISOString() },
      { id: 'act-2', type: 'CLIENT_ADDED', message: 'Cliente Lucía Martínez agregado', date: new Date().toISOString() },
    ],
  },
  automations: [
    {
      id: 'auto-1',
      name: 'Recordatorio 24h',
      description: 'Envía recordatorio un día antes de la cita',
      type: 'REMINDER',
      active: true,
      config: JSON.stringify({ channel: 'WhatsApp', message: 'Hola! Te recordamos tu cita mañana.' }),
      userId: DEMO_USER_ID,
      _count: { logs: 15 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'auto-2',
      name: 'Reactivación Inactivos',
      description: 'Contacta clientes que no vienen hace 30 días',
      type: 'REACTIVATION',
      active: false,
      config: JSON.stringify({ days: 30, message: 'Te extrañamos! Vuelve por un 10% desc.' }),
      userId: DEMO_USER_ID,
      _count: { logs: 5 },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};
